# POST http://127.0.0.1:7001/add 
# POST http://127.0.0.1:7001/newContext 

# Content-Type: application/x-www-form-urlencoded
# Content-Type: application/json

# name=qingshansima
# {
#   "name":"小红"
# }

POST http://127.0.0.1:7001/newRequest
Content-Type: application/json
token: 'qingshansima'

